# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fba049e5f77750ed2e64e8029651abf1f786bed7173083ce4899e62cb10229e96c5ae8a2942aed61c9402f5e5b79584bf44c68056eea3b3a02f7601cf22f0d0

test:
  secret_key_base: aad3e2766b83e43ecd838fb72e0a930b299539d445746c43ce9a0bc8259439823243aae82f08ca35070072c8fd989f8558ff17445cf3334c5e2c3e80f9193115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
